// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHUFduO7KiVwq44P1v1YnxbTo37bhh_PM',
    appId: '1:355422990462:android:e55b3d70839640e40d682f',
    messagingSenderId: '355422990462',
    projectId: 'cryptoconvertercurrencyassets',
    storageBucket: 'cryptoconvertercurrencyassets.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIXggloUngTrOrClZljV603zHMmE6BpK0',
    appId: '1:355422990462:ios:b578b96b5c0eeaca0d682f',
    messagingSenderId: '355422990462',
    projectId: 'cryptoconvertercurrencyassets',
    storageBucket: 'cryptoconvertercurrencyassets.firebasestorage.app',
    iosBundleId: 'com.whitelab.cryptocurrencyconverter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIXggloUngTrOrClZljV603zHMmE6BpK0',
    appId: '1:355422990462:ios:d4b8e6a6eddffb230d682f',
    messagingSenderId: '355422990462',
    projectId: 'cryptoconvertercurrencyassets',
    storageBucket: 'cryptoconvertercurrencyassets.firebasestorage.app',
    iosBundleId: 'com.example.cryptocurrencyconverter',
  );
}
