-- =============================================
-- SIMPLE DATABASE SETUP
-- =============================================
-- Run this in Supabase Dashboard > SQL Editor
-- Copy ALL of this and paste it, then click "Run"

-- 1. Create the exchange_rates table
CREATE TABLE IF NOT EXISTS public.exchange_rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(10) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    symbol VARCHAR(20),
    price_usd NUMERIC(30, 15) NOT NULL DEFAULT 0,
    change_percent_24h NUMERIC(10, 4) DEFAULT 0,
    is_crypto BOOLEAN NOT NULL DEFAULT false,
    market_cap NUMERIC(30, 2),
    volume_24h NUMERIC(30, 2),
    rank INTEGER,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create the fetch_logs table (tracks API fetches)
CREATE TABLE IF NOT EXISTS public.fetch_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fetched_at TIMESTAMPTZ DEFAULT NOW(),
    crypto_source VARCHAR(50),
    crypto_count INTEGER DEFAULT 0,
    fiat_count INTEGER DEFAULT 0,
    duration_ms INTEGER,
    success BOOLEAN DEFAULT true,
    error_message TEXT
);

-- 3. Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_exchange_rates_code ON public.exchange_rates(code);
CREATE INDEX IF NOT EXISTS idx_exchange_rates_is_crypto ON public.exchange_rates(is_crypto);
CREATE INDEX IF NOT EXISTS idx_fetch_logs_fetched_at ON public.fetch_logs(fetched_at DESC);

-- 4. Enable Row Level Security
ALTER TABLE public.exchange_rates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fetch_logs ENABLE ROW LEVEL SECURITY;

-- 5. Drop existing policies if they exist (to avoid conflicts)
DROP POLICY IF EXISTS "Allow public read on exchange_rates" ON public.exchange_rates;
DROP POLICY IF EXISTS "Allow service write on exchange_rates" ON public.exchange_rates;
DROP POLICY IF EXISTS "Allow public read on fetch_logs" ON public.fetch_logs;
DROP POLICY IF EXISTS "Allow service write on fetch_logs" ON public.fetch_logs;

-- 6. Create RLS policies
-- Anyone can READ exchange rates
CREATE POLICY "Allow public read on exchange_rates" 
ON public.exchange_rates FOR SELECT 
TO anon, authenticated
USING (true);

-- Only service role can INSERT/UPDATE/DELETE
CREATE POLICY "Allow service write on exchange_rates" 
ON public.exchange_rates FOR ALL 
TO service_role
USING (true)
WITH CHECK (true);

-- Anyone can READ fetch logs
CREATE POLICY "Allow public read on fetch_logs" 
ON public.fetch_logs FOR SELECT 
TO anon, authenticated
USING (true);

-- Only service role can write fetch logs
CREATE POLICY "Allow service write on fetch_logs" 
ON public.fetch_logs FOR ALL 
TO service_role
USING (true)
WITH CHECK (true);

-- 7. Grant permissions
GRANT SELECT ON public.exchange_rates TO anon, authenticated;
GRANT ALL ON public.exchange_rates TO service_role;
GRANT SELECT ON public.fetch_logs TO anon, authenticated;
GRANT ALL ON public.fetch_logs TO service_role;
